{
 "title": "Group Project 1",
 "time": { "from": "now-2y", "to": "now" },
 "panels": [
  {
   "title": "Project Demo",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Intro",
     "type": "text",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "options": {
      "content": "<a href='https://www.casimages.com/i/201008082927551409.png.html' target='_blank' title='Mon image'><img src='https://nsa40.casimages.com/img/2020/10/08/201008082927551409.png' border='0' alt='Mon image' /></a>"
     },
     "targets": [
      {
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
      }
     ]
    },
    {
     "title": "Tasks",
     "type": "text",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "options": {
      "content": "<a href='https://www.casimages.com/i/201008083401735631.png.html' target='_blank' title='Mon image'><img src='https://nsa40.casimages.com/img/2020/10/08/201008083401735631.png' border='0' alt='Mon image' /></a>"
     },
     "targets": [
      {
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
      }
     ]
    },
    {
     "title": "Phase 1",
     "type": "text",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 9 },
     "options": {
      "content": "<a href='https://www.casimages.com/i/201008082357589137.png.html' target='_blank' title='Mon image'><img src='https://nsa40.casimages.com/img/2020/10/08/201008082357589137.png' border='0' alt='Mon image' /></a>\n"
     },
     "targets": [
      {
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
      }
     ]
    },
    {
     "title": "Phase 2",
     "type": "text",
     "gridPos": { "h": 21, "w": 24, "x": 0, "y": 23 },
     "options": {
      "content": "<a href='https://www.casimages.com/i/201008083455325289.png.html' target='_blank' title='Mon image'><img src='https://nsa40.casimages.com/img/2020/10/08/201008083455325289.png' border='0' alt='Mon image' /></a>"
     },
     "targets": [
      {
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
      }
     ]
    },
    {
     "title": "Phase 3",
     "type": "text",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 44 },
     "options": {
      "content": "<a href='https://www.casimages.com/i/201008082726342296.png.html' target='_blank' title='Mon image'><img src='https://nsa40.casimages.com/img/2020/10/08/201008082726342296.png' border='0' alt='Mon image' /></a>"
     },
     "targets": [
      {
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Finances",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total due per customer",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  now() AS \"time\",\n  customerName AS metric,\n  sum(TotalCommande) AS \"TotalCommande\"\nFROM finances\ngroup by customerName\nORder by totalcommande desc;"
      }
     ]
    },
    {
     "title": "Turnover per country over the last 2 months ",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  now() AS \"time\",\n  country AS metric,\n  turnover\nFROM finances2\nORDER BY turnover\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Logistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Stock of the most ordered products",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  now() AS \"time\",\n  NomProduit AS metric,\n  QuantiteEnStock\nFROM logistics\nORDER BY now()\n"
      }
     ]
    },
    {
     "title": "Unit sold of the most ordered products",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  now() AS \"time\",\n  NomProduit AS metric,\n  NombreVendu\n\nFROM logistics\nORDER BY now()\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Human Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top sellers",
     "type": "stat",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "rawSql": "SELECT \nNOW() AS \"time\", \nconcat(lastname, \" \", firstname, \" - \", salesrepemployeenumber) AS metric, \nturnover \nFROM hr \norder by now();"
      }
     ]
    }
   ]
  },
  {
   "title": "Sales",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Products Sold by Category and by Month",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  date AS \"time\",\n  Catégorie AS metric,\n  QuantitéVendue AS \"QuantitéVendue\"\nFROM sales\nWHERE\n  $__timeFilter(date)\nORDER BY date"
      }
     ]
    }
   ]
  },
  {
   "title": "KPI",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Turnover per City",
     "type": "grafana-worldmap-panel",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 6 },
     "valueName": "total",
     "targets": [
      {
       "rawSql": "select ville, turnover, latitude, longitude from map;\n"
      }
     ]
    },
    {
     "title": "Best Customers",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "Orders" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  now() as \"time\",\n  customerName as metric,\n  nombredecommandes\n  from clientsfideles\n  where nombredecommandes >= 10\n  order by now()\n"
      }
     ]
    },
    {
     "title": "Stock Management",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
     "targets": [
      {
       "rawSql": "SELECT productname, quantityinstock,commandes,quantityinstock/commandes AS ratio\nFROM stocks\nORDER BY ratio DESC\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Tables",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Finances 1",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "rawSql": "SELECT customernumber, customerName, ordernumber, TotalCommande from finances\norder by customerName, TotalCommande;"
      }
     ]
    },
    {
     "title": "Finances 2",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
     "targets": [
      { "rawSql": "SELECT * from finances2;\n" }
     ]
    },
    {
     "title": "Human Resources",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
     "targets": [
      { "rawSql": "select * from hr;\n" }
     ]
    },
    {
     "title": "Logistics",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
     "targets": [
      { "rawSql": "SELECT * from logistics;\n\n" }
     ]
    },
    {
     "title": "Sales",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
     "targets": [
      {
       "rawSql": "SELECT Catégorie, AnnéeEnCours, MoisEnCours, QuantitéVendue, AnnéePrécédente, QuantitéAnnéePrécédente, RateOfChange from sales;"
      }
     ]
    },
    {
     "title": "Turnover per City",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
     "targets": [
      {
       "rawSql": "select turnover, pays, ville from map;\n"
      }
     ]
    },
    {
     "title": "Best Customers ",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 54 },
     "targets": [
      {
       "rawSql": "select * from clientsfideles\nwhere nombredecommandes>= 10;"
      }
     ]
    },
    {
     "title": "Stock Management",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
     "targets": [
      {
       "rawSql": "SELECT commandes, productcode, quantityInStock, productname from stocks;"
      }
     ]
    }
   ]
  }
 ]
}